#!/usr/bin/env python3
"""Generate the embedded Qt UI catalog without requiring Qt Linguist tools."""
import json
from pathlib import Path
import sys

root = Path(__file__).resolve().parent.parent
source = root / "translations/ui_catalog.json"
output = root / "src/ui/translations_catalog.hpp"
catalog = json.loads(source.read_text(encoding="utf-8"))
keys = None
for language, messages in catalog.items():
    if keys is None:
        keys = set(messages)
    if set(messages) != keys:
        raise ValueError(f"Incomplete catalog: {language}")
    if any(not value for value in messages.values()):
        raise ValueError(f"Empty translation: {language}")
text = json.dumps(catalog, ensure_ascii=False, sort_keys=True, indent=2) + "\n"
generated = ('// Generated by translations/generate_catalog.py; edit translations/ui_catalog.json.\n'
             '#pragma once\n\nnamespace hyprcapture::ui::detail {\n'
             'inline constexpr const char kUiTranslationCatalog[] = R"HYPRCAPTURE_JSON(\n'
             + text + ')HYPRCAPTURE_JSON";\n}\n')
if "--check" in sys.argv:
    if not output.exists() or output.read_text(encoding="utf-8") != generated:
        raise SystemExit("Embedded catalog is stale; run translations/generate_catalog.py")
else:
    output.write_text(generated, encoding="utf-8")
