#!/usr/bin/env python3
"""Embed the vendored Google Material Symbols; no network access required."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
icons = sorted((root / 'assets/icons/material-symbols').glob('*.svg'))
lines = ['// Generated by scripts/generate_material_icons.py. Do not edit.',
         '// Google Material Symbols, Apache-2.0; see assets/icons/material-symbols/LICENSE.',
         '#pragma once', '#include <string_view>',
         'namespace hyprcapture::ui {',
         'inline std::string_view materialSvg(std::string_view name) {']
for icon in icons:
    name = icon.stem.removesuffix('_24px')
    lines.append(f'    if (name == "{name}") return R"svg({icon.read_text().strip()})svg";')
lines += ['    return {};', '}', '}']
(root / 'src/ui/material_icons_catalog.hpp').write_text('\n'.join(lines) + '\n')
